# Bind service account "cd" to role "admin" in namespace "homework"
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homework-admin-binding
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  kind: Role
  name: admin-homework
  apiGroup: rbac.authorization.k8s.io
