apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-cm
  namespace: homework
data:
  file: |
    randomValue1= apple
    randomValue2="Aldebaran"
    randomValue3="451"
    randomValue4="2025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8000;
          server_name  0.0.0.0;
          location / {
              root   /homework;
              index  index.html index.htm;
          }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: get-metrics-cm
  namespace: homework
data:
  get-metrics.sh: |
    #!/bin/bash
    touch /init/metrics.html
    KUBE_API_SERVER=${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    curl -k -v -H "Authorization: Bearer $TOKEN" https://$KUBE_API_SERVER/metrics >> /init/metrics.html

