image:
  tag: 3.5.2
listeners:
  client:
    protocol: SASL_PLAINTEXT
listeners:
  interbroker:
    protocol: SASL_PLAINTEXT
listeners:
  external:
    protocol: SASL_PLAINTEXT
persistence:
  enabled: false
broker:
  replicaCount: 1
#controller:
#  replicaCount: 1

