apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homework-storage-class
  resourceVersion: "0"
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
