apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---
apiVersion: v1
kind: Secret
metadata:
  name: token-cd
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
